# Effects of actions on working memory

Actions may be considered extensions of memory, affording strategies for preserving information beyond what the capacity of working memory might typically allow. While study of speech-based sensory-motor phenomena is quite advanced, understanding how spatial and haptic sensory and motor functions influence memory remains under-explored. Talks in this session investigate non-speech sensory and motor influence on working memory, including motion, spatial awareness, and rhythmic pattern.

## Schedule

This discussion session will take place 1 September from 9:00 - 10:30 (UK) / 10:00 - 11:30 (Switzerland/France) / 17:00 - 18:30 (Japan).

## Discussants

Get in touch with Louise Brown Nicholls (l.nicholls@strath.ac.uk; \@LNichollsStrath) or David M. Spaulding (david.m.spalding@strath.ac.uk;  \@DSpaldingStrath) with your ideas for questions and discussion points.

## Abstracts

Recorded talks will be available from 14 August 2020.

### The Hebb repetition effect in reproduction of nonverbal rhythms

*Yoshiyuki Ueda (Kyoto University) & Satoru Saito*

*Email: ueda.yoshiyuki.3e@kyoto-u.ac.jp*

The Hebb repetition effect is a phenomenon that repeated presentation of the same sequence of memory items facilitate immediate serial recall performance of the sequence. This effect, which is predominantly tested in verbal domain, is assumed to exhibit the contributions of long-term knowledge to working memory. One of the notable characteristics of this effect is its strong dependence on presentation timing, as reflected in the decreased effect, which was observed when the temporal structures varied in each presentation of the repeated sequence. This suggests that the temporal structures are also learnt over repetition and might contribute to the Hebb repetition effect. The present study directly tested this assumption and investigated what mechanisms underlie it. In a series of immediate recall experiments, participants were presented multiple beep tones with rhythms and asked to reproduce it manually. In each experiment, one rhythm (the Hebb tone sequence) was frequently presented than others (the filler sequence). In Experiment 1, we confirmed the Hebb repetition effect in reproduction of nonverbal rhythms. In Experiment 2, participants were asked to engage in articulatory suppression during encoding the rhythm. The results showed no Hebb repetition effect under this situation, suggesting that either dual task demand or disruption of articulatory mechanisms might interfere with learning of temporal structures. In Experiment 3, participants were asked to perform either a visuospatial drawing task or articulatory suppression during the encoding. The results showed that the Hebb repetition effect for nonverbal rhythms was observed only for participants who performed the drawing task, indicating that the disappearance of the Hebb repetition effect in Experiment 2 was not due to the presence of dual-task demand. The findings reported here suggest that the temporal structure can be learnt over repetition through articulation related mechanisms.

### Translating words into actions in working memory: a role for spatial-motoric coding in the enacted recall advantage

*Richard Allen (University of Leeds), Guangzheng Li, Alan Baddeley, & Graham Hitch*

*Email: r.allen@leeds.ac.uk*

The phonological loop component of working memory has benefited extensively from its application to understanding tasks of practical relevance.  This is rather less so for the visuo-spatial sketchpad component although an exception is the recent range of studies concerned with the capacity to follow and enact spoken instructions in which enactment by the participant at recall has consistently been shown to produce enhanced performance.  This is generally interpreted as reflecting a generated spatial-motoric plan, though the detailed characteristics of such a plan remain to be explored. We describe five experiments investigating this, comparing verbal and enacted recall of a series of actions under different concurrent task conditions involving repetitive actions that involve either fine motor (finger-based) or gross motor (arm-based) movement. A general advantage from enacted recall was observed across experiments, together with a tendency for concurrent action suppression to impair recall. The enacted recall advantage was reduced or abolished under certain concurrent action conditions, depending on factors such as complexity, familiarity, and gross vs. fine motor movement. We conclude that our results are consistent with the view that spatial motoric plans are constructed in working memory for anticipated action.

### Visuospatial Bootstrapping: Spatialization facilitates verbal memory in a range of learning and memory tasks

*Stephen Darling (Queen Margaret University)*

*Email: sdarling@qmu.ac.uk*

There is growing evidence that spatial information that is available within visually presented materials can facilitate performance in verbal tasks. A frequently replicated finding demonstrates that immediate verbal serial recall is facilitated if the to-be-remembered items are presented in the familiar 2-dimensional PIN keypad. In this presentation I will summarise the key aspects of this literature, expanding from what is already known about immediate serial recall to research on long term sequence learning. I will then introduce a couple of recent studies. The first showed that bootstrapping-like responses occur in serial recall for non-numeric materials. The second showed that bootstrapping responses also occurred during ‘running span’ tasks. Running span tasks are those where a participant is asked to remember the last items in a sequence, but is unaware of the sequence length, and so must keep the responses continually updated. Spatialized displays facilitated running span task recall. Additionally, the size of this benefit did not seem to be contingent on the speed of presentation. Overall, these findings tend to suggest that spatialization can enhance verbal memory when appropriate displays are used. This enhancement can occur in a range of different learning and memory tasks and operates relatively quickly and hence probably automatically.

### Bootstrapping the visuospatial bootstrapping effect (and testing its spatialisation)

*Alessandro Guida (Universitè Rennes)*

*Email: alessandro.guida.psychology@gmail.com*

A decade ago, Darling and Havelka (2010) observed that when sequences of digits are visually presented within a numerical keypad on the screen (like those on phones), memory span increases. They called this phenomenon visuospatial bootstrapping (VB) to reflect the support of verbal memory by visuospatial memory. I will present two experiments that further investigate the power of VB and its consequence. The aim of the first experiment was to answer the following question: can the VB effect still emerge without actually presenting a keypad on the screen? For this purpose, a three-phase experiment was designed. During the first phase, the performances of two groups of participants in an immediate serial recall task were compared: the first group saw sequences of one-digit numbers displayed on a screen within a keypad (the keypad group) whereas the second group heard the (same) sequences (the auditive group). After this first phase, participants from both groups underwent an 18 minutes training phase in order to learn how to visualize in their mind’s eye a numerical keypad and use it to encode sequences. Finally, in the third phase, participants were tested again in an immediate serial recall task similarly to phase one. Results showed that the VB effect can obtained without displaying a numerical keypad. The second experiment also involved a keypad group and an auditive group and was designed to investigate if the spatial representation of both groups were comparable. For this purpose, we adapted a paradigm from the study of the SPoARC effect (Spatial Positional Association Response Codes), which enables to test for a left-to-right or a right-to-left spatialization (or an absence of horizontal spatialization). Results showed that for both groups the spatial representation followed a left-to-right direction, compatible with the idea that participants associated the keys “1”, “4”, and “7” to left, “2”, “5”, and “8” to middle and “3”, “6”, and “9” to right.

### The role of verbal working memory in gesture/speech integration: The need of taking individual differences into account

*Kendra Kandana Arachchige (University of Mons), Henning Holle, Mandy Rossignol, Isabelle Simoes Loureiro, & Laurent Lefebvre*

*Email: kendra.kandanaarachchige@umons.ac.be*

Iconic gestures (IG) are characterized by a formal relationship between the gesture and the speech it accompanies. It is now known that presenting semantically congruent (SC) IG (i.e. that match the spoken utterance) compared to semantically incongruent (SI) ones improves comprehension. Since they occur concurrently to speech and are subject to on-line processing, Wu and Coulson (2014) suggested that verbal working memory (vWM) may play a role in gesture/speech integration (GSI). In a first study, participants were asked to complete a gender classification task (GCT), embedded in a vWM task where they were asked to remember words. Participants were presented with one or four words to remember (vWM task). The GCT consisted of videos of a gesture enacted by a man or a woman accompanied by a SC or SI audio from a man or woman's voice. Participants were asked to discriminate, as fast as possible, the gender of the voice. They then saw a list of words and had to click on the ones previously seen. This study failed to demonstrate an involvement of the vWM on GSI. We suggest that this may be due to not taking individual differences (ID) in vWM into account. We hence conducted a second study where we individualized the vWM task. We expect a main effect of SC shown by reduced reaction times for the SC condition compared to SI, and an interaction between vWM load and SC. 27 healthy French-speaking participants (6 men; Mage = 22.85; SD=0,79) completed the Digit Span Task, determining the span for the vWM. In the vWM, participants were here presented with one (low) or several (high load, matching their span) words. The GCT remained unchanged. A 3-way repeated-measures ANOVA (load(2)x semantics(2)xgender(2)) yielded significant main effect for semantics (F1,26 = 4,26; p = 0.04) with a faster processing of SC pairs, and an interaction effect load x semantic (F1,26 = 4,45; p = 0.04). These results suggest that vWM is indeed involved in GSI, but only when ID are taken into account.

### Working memory at play: Two studies with volleyball players

*Elisa Bisagno (University of Modena and Reggio Emilia), Sergio Morra, & Francesca Vitali*

*Email: elisa.bisagno@unimore.it*

M capacity (Pascual-Leone, 1987; Pascual-Leone & Goodman, 1979) has been found predictive of the performance in many perceptual, linguistic and reasoning tasks. However, it has been less studied "in action", for example, in the sport domain. We aimed at testing the role of M capacity in motor learning (Study 1) and sport performance (Study 2) in samples of youth volleyball players. Study 1 (Bisagno & Morra, 2018): 105 youth female volleyball players (5-17 years old and a group of "experts", i.e. adults with at least 10 years of volleyball experience) were engaged in WM tests and volleyball attack tasks of increasing difficulty, modelled via task analysis and scored in terms of "correct execution" and "precision". We also considered each athlete's experience (years of practice). The best predictor of the correct execution was the WM capacity, while experience was the only significant predictor of the precision. Also, a prediction analysis of cross-classification confirmed that M capacity sets a limit in learning certain attack gestures. Examples of our task analysis will be presented. Study 2 (under review): 114 youth female volleyball players (11-18 years old) were engaged in WM capacity and Executive Functions (updating, inhibition and shifting) tests. They also completed self-report measures with respect to their attentional style and precompetitive emotions. For each volleyball player, at least three competitions were recorded and scored by two expert observers. An individual performance index based on every gesture performed during the games, and controlled for the team performance, was computed. An M capacity-updating factor resulted as the main predictor of the volleyball players' performance, together with high-arousal "unpleasant" emotions. A moderation of emotional correlates on the relation between WM and performance was found. Taken together, these studies underline the role of capacity in predicting both motor learning and performance in volleyball.

### Does sensorimotor arousal influence memory functioning? A test of embodied view of memory using short term immobilization

*Jeremy Villatte (Universitè Poitiers), Laurence Taconnat, & Lucette Toussaint*

*Email: jeremy.villatte@univ-poitiers.fr*

In line with embodied views of cognition, growing evidence suggests that memory functioning is based on sensorimotor systems. Hence, different models (Versace et al., 2014; Briglia et al., 2018) assume that memory encoding rely on integration of sensorimotor information while retrieval is based on its reactivation. In the present study, we hypothesized that some memories are more strongly related to specific sensorial or motor systems that are crucial for their integration and reactivation. Example of this somatotopic-related memories could be observed using manipulable objects as stimuli. Thus, hand-related information is likely to play a more central role in memory of manipulable objects than information from other sensorimotor systems. In order to assess the specific contribution of manual sensorimotor system to memory of manipulable objects, we used a short term upper limb immobilization design. Twenty-four hours before the beginning of the experiment, a rigid splint was fixed on the dominant (right) hand of the participants assigned to the experimental group. The splint immobilized their hand, wrist and fingers. An immobilization vest restrained the move of their right arm to ensure they keep their hand at rest. Previous studies have shown that decreased arousal induced by immobilization elicit quick updating of manual sensorimotor representations (Meugnot & Toussaint, 2015). Once twenty-four hours of immobilization elapsed, participants undergo a manipulable and non-manipulable objects pictures recognition task. We expected delayed response time for immobilized participants, in particular for correct recognitions (hits) of manipulable object. However, contrary to our prediction, hits for manipulable objects were faster for immobilized than for control group F (1,44) = 9,66, p<.01. We suggest that this surprising result is due to adaptive processes. Thus, immobilization could reduce amount of available information in memory, leading to quicker processing. 

### Inhibition of Return and/or facilitation in working memory?

*Caro Hautekiet (University of Geneva), Naomi Langerock, & Evie Vergauwe*

*Email: Caro.Hautekiet@unige.ch*

Research in perception has shown that when a target is presented in a previously cued location, there is a short facilitative effect for responding to this target. Following an attentional shift away from the cued location, the facilitative effect turns into an inhibitory effect. The latter is better known as the Inhibition of Return (IOR) effect (Posner & Cohen, 1984). Some researchers have looked at the analogue of the effect in working memory. However, the emerging pattern appears contradictory. On the one hand, Vergauwe & Langerock (2017) found a facilitative effect for an item that was just the object of focused attention in working memory (i.e., the just-refreshed item). On the other hand, Johnson and colleagues (2013) found lowered accessibility for the just-refreshed item (i.e., an IOR-like effect). We aimed to understand the consequences of an item being in the focus of attention. Is it more accessible (i.e., facilitation) or less accessible (i.e., inhibition)? To address this question, we examined the role of two variables, based on the perception literature: (1) the particular task to be performed, and (2) timing parameters. Doing so, we showed (1) that the task to be performed modulates the effect of refreshing on response times to the target, such that inhibition was observed when refreshed vs. unrefreshed words were presented in a simple reading task, whereas facilitation was observed refreshed vs. unrefreshed words were presented in a manual lexical decision task. Furthermore, (2) in sharp contrast with what has been observed in perception, manipulating the time between cue and probe in the manual lexical decision task did not result in a cross-over from facilitation to inhibition, even when very long cue-target onset asynchronies were used. Thus, like Vergauwe & Langerock (2017), we found evidence that an item in the focus of attention is more accessible in a manual lexical decision task.

### Visuo-spatial working-memory In body-awareness: does recalling locations helps perceive its own body?

*Sara Salgues (Universitè Lyon), Gaën Plancher, & George A. Michael*

*Email: Sara.salgues@univ-lyon2.fr*

Body-awareness requires maintaining body representations in focus. The perception of spontaneous sensations (SPS) in the absence of tactile stimulation of the skin would contribute to body-awareness. Vision and attention are predominant factors of body-awareness and of SPS perception, and contribute to the maintenance of representations in working memory. Lesions in the parietal lobe were found to impair the body-representation maintenance without visual focus, causing one to lose awareness of its body-parts within seconds. Given that spatial-vision and spatial-attention play an important role in SPS perception, it was hypothesized that visuo-spatial working memory (VSWM) would contribute to body-awareness, and thus modulate the perception of SPS. Computed VSWM tasks, in the form of a Brown-Peterson and a complex span tasks, and a standard task of SPS, investigating the perception of sensations perceived in the absence of any tactile stimulation on the hands, were proposed to participants. The effect of decay, interference and cognitive load on recall performances were extracted from the VSWM tasks. Correlational analyses were carried out between these values and SPS. This study found that slow decay, and low rates of forgetting due to cognitive load were mainly associated with higher frequency of SPS over the hand. Opposite patterns were observed for the interference: individuals with low rate of forgetting perceived more SPS on less sensitive area, and conversely. In conclusion, greater ability in working memory would contribute to a better perception of SPS, either through an increment of their frequency on the hand, or through a better sensitivity to SPS on less sensitive area of the hand. On previous studies, the perception of SPS on less sensitive area of the hand was associated to interoceptive abilities, also strongly linked to body-awareness. These findings allow us to discuss the involvement of VSWM in body-awareness.

