# How verbalization and language impact working memory

How does verbalization impact memory for information, whether for words, images, or sounds? What does our understanding about interactions between verbalization and working memory performance suggest about the structure of a working memory system? [Talks in this session](https://www.youtube.com/playlist?list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE) consider these topics.

## Schedule

This discussion session will take place 1 September from 15:00 - 16:30 (UK) / 16:00 - 17:30 (Switzerland/France) / 9:00 - 10:30 (USA - Central Time Zone).

## Discussants

Get in touch with Gaia Scerif (gaia.scerif@psy.ox.ac.uk; \@GaiaScerif) or Alessandra Souza (a.souza@psychologie.uzh.ch;  \@A_SSouza) with your ideas for questions and discussion points.

## Abstracts

Recorded talks will be available from 14 August 2020.

### [When does spontaneous verbal rehearsal emerge in children, and how does it affect memory recall? A multi-lab replication of Flavell, Beach and Chinsky (1966)](https://www.youtube.com/watch?v=xfySmou6tFk&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=4)

*Candice C. Morey (Cardiff University), Emily M. Elliott, Angela AuBuchon, et al.* 

*Email: moreyc@cardiff.ac.uk* 

*Twitter: \@CandiceMorey*

Work by Flavell, Beach, and Chinsky (1966) indicated a change in the spontaneous production of overt verbalization behaviors when comparing young children (age 5-6) to older children (age 10). Despite the critical role that this evidence of a change in verbalization behaviors plays in modern theories of cognitive development and working memory, there has only been one other published near-replication of this work (Keeney, Cannizzo, & Flavell, 1967). This Registered Replication Report relied upon 17 labs who contributed their results to a larger and more comprehensive sample of children (N=977), with roughly equal numbers of 5-, 6-, 7-, and 10-year-olds. We assessed memory performance and the presence or absence of verbalization behaviors of young children across this age range, and determined that the original pattern of findings was largely upheld. We observed a clear increase in verbalization between 5- and 7-year-olds; however, the further increase between 7- and 10-year-olds that Flavell et al. originally reported was much less clear. Verbalization was also more prevalent in the young children in our sample than it was in Flavell et al.'s sample, which seems inconsistent with the proposition that verbal rehearsal strategies are unavailable to children under 7. With our large sample, we were able to extend Flavell et al.'s findings with respect to the benefit of verbalization for recall. Children who verbalized, whatever their age, recalled longer sequences than children who did not. The implications for theories of working memory development arising from these findings will be discussed. 

### [How do verbal labels influence children's visual working memory?](https://www.youtube.com/watch?v=slaiifXmW3E&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=5)

*Clara Overkott (University of Zurich), Alessandra Souza, & Candice C. Morey*

*Email: c.overkott@psychologie.uzh.ch*

Storage of information in visual working memory (WM) is highly constrained and only a limited amount of representations can be maintained vividly in mind. Verbal labeling can be used to improve visual WM. Research with young adults showed that labeling increases both the quantity and quality of the visual information retained in mind, and that adults tend to spontaneously use this strategy. So far, it is unclear whether children can and do use this strategy to improve their visual WM. In this study we aimed to assess developmental changes in verbal labeling effects on the storage of continuous (i.e., fine-grained) and categorical (more prototypical) color information, manipulating whether labeling was spontaneous or experimenter-instructed. Children (5-7 and 8-11 years) and young adults (18-35 years) did a delayed estimation task in which they memorized colored candies varying on a continuous scale. During memorization, they were prompted to remain silent, label the colors, or to say irrelevant syllabi ("bababa") thereby discouraging verbal labeling. At test, the color of the candies was reproduced on a color wheel. Results showed that children of both age groups were able to spontaneously use verbal labels and engage in experimenter-instructed labeling. Across all age groups, experimenter-instructed labeling showed the highest labeling benefit. There was a developmental labeling benefit trend for both spontaneous and experimenter-induced labeling. Mixture modeling on the format (categorical or continuous) in which the colors were stored, and their precision showed that labeling increased both categorical and continuous storage as well as in precision for children over 7-years-old and under 7-years-old, as well as adults. This suggests that experimenter-instructed and spontaneous labeling benefits quantity and quality of visual information similarly across development.

### [Short-term memory for music: the role of the vocal motor system?](https://www.youtube.com/watch?v=4y2fEWh88_o&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=3)

*Simon Gorin (University of Geneva) & Emma Greenspon*

*Email: gorinsimon@gmail.com*

Whether people engage in covert rehearsal to maintain musical information in short-term memory (STM) is unclear. In this study, we tested the hypothesis that the maintenance of pitch information in STM is supported by the vocal motor system. More precisely, we tested the idea that the rehearsal of pitch information relies on the translation of an auditory target into the motor codes required to reproduce that target. The same sensorimotor translation mechanism is assumed to operate in pitch imitation, and studies on singing abilities showed that the closest from participants' voice is the to-be-imitated the target, the most accurate is their imitation. Consequently, if the vocal motor system supports the maintenance of pitch information in a recognition task for pairs of melodies, we should observe better recognition performance with material sounding with the timbre of a synthetic voice than a piano (Experiment 1) and for melodies with the timbre of a real voice than a synthetic voice (Experiment 2). Also, it is expected that the effect of the type of timbre should disappear under articulatory suppression but not under manual tapping as only the former recruits the vocal motor system. In Experiment 1, we observed no effect of the type of timbre. In Experiment 2, the participants showed an advantage such that recognition was better for melodies with a real voice compared to melodies with a synthetic voice. However, as expected, this advantage disappeared with articulatory suppression. Our results suggest the existence of a link between the vocal motor system and the mechanism involved in pitch maintenance in STM.

### [The role of working memory maintenance mechanisms in false recall](https://www.youtube.com/watch?v=w48taKeak_E&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=6) 

*Marléne Abadie (Aix Marseille University), Amelie Troubat, Christelle Guette, Valérie Camos*

*Email: marlene.abadie@univ-amu.fr*

Recent research revealed that working memory (WM) maintenance plays a crucial role in the occurrence of false recognition of semantically related lures (Abadie & Camos, 2018). The present study explores the role of WM maintenance mechanisms, more specifically articulatory rehearsal and attentional refreshing, in false recall of semantic associates. In a Brown-Peterson paradigm, participants maintained lists of four semantically related words while performing a concurrent task. The attentional demand of the concurrent task and the presence of a concurrent articulation during the task were varied orthogonally to manipulate the availability of refreshing and rehearsal, respectively. Then, participants recalled the words immediately after the retention interval and in a delayed task occurring after each block of 10 trials. Results of two experiments provided decisive evidence that preventing the use of rehearsal or of refreshing reduces immediate correct recall. Interestingly, it also specifically increases immediate false recall of unpresented semantic associates with a stronger impact of articulatory suppression. Consistently in the two experiments, there was evidence against an effect of articulatory rehearsal on delayed recall performance. Refreshing also did not affect delayed recall performance in Exp.1. By contrast, in Exp. 2, in which participants were forced to recall the 40 words, i.e., the same number of words as words presented, there was strong evidence that preventing refreshing increased delayed correct recall and had no effect on false recall. These findings support the idea that rehearsal prevents the occurrence of short-term false memories but has no effect in the longer term. Refreshing would also reduce semantic distortions in the short-term, but the results are less clear as to its potential longer-term impact.  

### [False memories in children's working memory](https://www.youtube.com/watch?v=cfXObos3IcM&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=2&t=5s)

*Rousselle Manon (Aix Marseille University), M. Abadie, V. Camos, & A. Blaye*

*Email: manon.rousselle-jacquier@univ-amu.fr*

Studies indicate that a memory can be distorted after only a few seconds (Atkins & Reuter-Lorenz, 2008). Working memory (WM) maintenance mechanisms seem to determine the occurrence of false memory at short-term (Abadie & Camos, 2018). In this study, we examined this phenomenon by comparing the occurrence of false memories in 4 y.o children, who do not yet use any WM maintenance mechanisms, and 8 y.o children, who spontaneously use maintenance strategies (Oftinger & Camos, 2016).  Children performed a Brown-Peterson task in which they had to memorize semantically related items lists. Then they did an 8-second concurrent task. The difficulty of this task was varied to manipulate maintenance of memory items through WM. Afterwards, children performed a recognition task composed of target items, and of distractors semantically related and unrelated to the memory items. Results provided substantial evidence against an effect of age on correct recognition of targets and indicated that 4 y.o. falsely recognized related distractors as targets more often than 8 y.o. Unfortunately, our manipulation of WM maintenance mechanisms was probably not strong enough to affect children recognition performance. Data were also analyzed with the conjoint recognition model of the Fuzzy-trace theory (Brainerd et al., 1999) to estimate the contribution of gist and verbatim memory to recognition performance. Interestingly, 8 y.o. retrieved more gist and verbatim memory than 4 y.o. These findings suggest that both gist and verbatim memory increase with age which specifically reduce false recognition in working memory. 

### [Syntax, morphosyntax, and serial recall: How language supports short-term memory for order](https://www.youtube.com/watch?v=_7IVG-xiWGg&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=2)

*Judith Schweppe (University of Erfurt), Friederike Schuette & Marie Hellfritsch*

*Email: judith.schweppe@uni-erfurt.de*

In the classic view of verbal short-term memory, immediate recall of verbal sequences is achieved by maintaining phonological representations via articulatory rehearsal, while the influence of other linguistic information is negligible. According to language-based accounts, short-term retention of verbal material is inherently bound to language production and comprehension, thus also influenced by semantic or syntactic factors. In line with this, serial recall of word lists is better when they are presented in a canonical word order for English rather than in a non-canonical order, e.g., when adjectives precede nouns rather than vice versa, even when they are semantically unrelated (Perham, Marsh, & Jones, 2009, QJEP). However, in many languages, grammaticality is not exclusively determined by word order. In German, for instance, an adjective-noun sequence is grammatical only if the adjective is inflected in congruence with the noun's person, number, and grammatical gender. Therefore, we investigated whether similar effects of syntactic word order occur in serial recall of lists in German. In a modified replication of Perham et al.'s study, we presented lists of 3 pairs of adjectives and nouns. We manipulated ordering (adjective-noun vs noun-adjective) and morphosyntactic congruence between nouns and adjectives within pairs (adjectives inflected vs uninflected). Recall performance benefited from an adjective-noun order only when adjectives were inflected. However, recall for the lists with uninflected adjectives was as good as in the most grammatical condition. As uninflected adjectives are shorter, this may be due to a confound with word length, an assumption we aim to test in a follow-up experiment. Nonetheless, the current findings are in line with language-based models and indicate that, in a language that determines grammaticality in an interplay of syntactic and morphosyntactic factors, word order alone is not sufficient to improve verbal short-term memory.

### [Short-term memory (digit) span scores as a consequence not cause of language learning](https://www.youtube.com/watch?v=89QGpqjTuVw&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=8&t=0s)

*Gary Jones (Nottingham Trent University), Lucy V. Justice, Francesco Cabiddu, Bethany J. Lee, Lai-Sang Iao, Natalie Harrison, Bill Macken*

*Email: gary.jones@ntu.ac.uk*

Such is the consistency by which performance on measures of short-term memory (STM) increase with age that developmental increases in STM capacity are largely accepted as fact. Maturational capacity increases show strong links to higher order cognitive function - particularly language learning - that place STM at the heart of any explanation of such learning. However, our analysis of a robust but almost ignored finding - that span for digit sequences (the traditional measure of STM) increases at a far greater rate than span for other verbal material - fundamentally undermines the assumption that increased performance in STM tasks is underpinned by developmental increases in capacity. We show that this digit superiority with age effect is explained by the relatively greater linguistic exposure to random sequences of digits versus other stimuli such as words. A simple associative learning process that learns incrementally from exposure to language accounts for the effect, without any need to invoke an STM mechanism, much less one that increases in capacity with age. By extension, using corpus data directed at 2-3 year old children, 4-6 year old children, and adults, we show that age-related performance increases with other types of verbal material are equally driven by the same basic associative learning process operating on the expanding exposure to language experienced by the child. Our results question the idea that tests such as digit span are measuring a dedicated system for the temporary maintenance and manipulation of verbal material, and as such have implications for our understanding of those aspects of child development that are usually accounted for with respect to the operation of such a system. In particular, our results suggest that increases in STM performance do not play a causal role in language learning, but rather language learning itself is what causes increased performance in verbal STM tasks.

### [Working memory and language actions: Load effects on quality control in preschool children's production of novel syntax](https://www.youtube.com/watch?v=Pfgap7sHQpY&list=PLbongzUA9kndPFxbqu_jvA2oyy7AdHPSE&index=7)

*Eryn Adams (University of Missouri) & Nelson Cowan*

*Email: erynadams@mizzou.edu*

Working memory is widely accepted as a necessary resource for a wide variety of cognitive abilities. Developmental work has shown that as working memory capacities increase, so too does the ability to successfully perform other cognitive tasks, including language comprehension and production. The present work demonstrates effects of working memory availability on language production. Whereas most of the previous research linking working memory to language development has been correlational, we experimentally varied the working memory load during concurrent language production in children 4-5 years old. Participants (N=36) were asked to repeat verbatim the previously heard, passive-voice descriptions of images displaying transitive-verb actions. These responses were performed while children sometimes retained a spatial-visual or verbal working memory load to be recalled after sentence production. Responses were coded for either maintaining the relatively unfamiliar passive voice of a previously heard description of the picture, or changing the syntax to a more familiar, active voice. Surprisingly, children were more likely to use the active voice when there was no concurrent working memory load. Under a load, children more often used the passive voice, as they were instructed to do, but produced more errors while doing so (including some nonsensical renditions such as the girl was watered by the flower). We propose that working memory, when available, is used to impose a quality-control process whereby the semantic fidelity of the response to the stimulus picture is preserved, here at the expense of disregarding the experimental instruction to reproduce the passive voice.







