# Effects of context and knowledge on working memory

What are the mechanisms underlying the influence of long-term memory knowledge (e.g., semantic or feature similarity, chunking) on working memory? Talks in this session address topics such as how these LTM influences are at play at the level of encoding, relative to at retrieval, and whether we can determine the direction of LTM-WM relationships (e.g., language learning and verbal working memory)? Other talks in this session consider factors such as attention, refreshing and emotion in relation to the effects of context and knowledge on working memory.

## Schedule

This discussion session will take place 2 September from 11:30 - 13:00 (UK) / 12:30 - 14:00 (Switzerland/France) 

## Abstracts

Recorded talks will be available from 14 August 2020.

### Syntax, morphosyntax, and serial recall: How language supports short-term memory for order

*Judith Schweppe (University of Erfurt), Friederike Schuette & Marie Hellfritsch*

*Email: judith.schweppe@uni-erfurt.de*

In the classic view of verbal short-term memory, immediate recall of verbal sequences is achieved by maintaining phonological representations via articulatory rehearsal, while the influence of other linguistic information is negligible. According to language-based accounts, short-term retention of verbal material is inherently bound to language production and comprehension, thus also influenced by semantic or syntactic factors. In line with this, serial recall of word lists is better when they are presented in a canonical word order for English rather than in a non-canonical order, e.g., when adjectives precede nouns rather than vice versa, even when they are semantically unrelated (Perham, Marsh, & Jones, 2009, QJEP). However, in many languages, grammaticality is not exclusively determined by word order. In German, for instance, an adjective-noun sequence is grammatical only if the adjective is inflected in congruence with the noun's person, number, and grammatical gender. Therefore, we investigated whether similar effects of syntactic word order occur in serial recall of lists in German. In a modified replication of Perham et al.'s study, we presented lists of 3 pairs of adjectives and nouns. We manipulated ordering (adjective-noun vs noun-adjective) and morphosyntactic congruence between nouns and adjectives within pairs (adjectives inflected vs uninflected). Recall performance benefited from an adjective-noun order only when adjectives were inflected. However, recall for the lists with uninflected adjectives was as good as in the most grammatical condition. As uninflected adjectives are shorter, this may be due to a confound with word length, an assumption we aim to test in a follow-up experiment. Nonetheless, the current findings are in line with language-based models and indicate that, in a language that determines grammaticality in an interplay of syntactic and morphosyntactic factors, word order alone is not sufficient to improve verbal short-term memory.

### Short-term memory (digit) span scores as a consequence not cause of language learning

*Gary Jones (Nottingham Trent University), Lucy V. Justice, Francesco Cabiddu, Bethany J. Lee, Lai-Sang Iao, Natalie Harrison, Bill Macken*

*Email: gary.jones@ntu.ac.uk*

Such is the consistency by which performance on measures of short-term memory (STM) increase with age that developmental increases in STM capacity are largely accepted as fact. Maturational capacity increases show strong links to higher order cognitive function - particularly language learning - that place STM at the heart of any explanation of such learning. However, our analysis of a robust but almost ignored finding - that span for digit sequences (the traditional measure of STM) increases at a far greater rate than span for other verbal material - fundamentally undermines the assumption that increased performance in STM tasks is underpinned by developmental increases in capacity. We show that this digit superiority with age effect is explained by the relatively greater linguistic exposure to random sequences of digits versus other stimuli such as words. A simple associative learning process that learns incrementally from exposure to language accounts for the effect, without any need to invoke an STM mechanism, much less one that increases in capacity with age. By extension, using corpus data directed at 2-3 year old children, 4-6 year old children, and adults, we show that age-related performance increases with other types of verbal material are equally driven by the same basic associative learning process operating on the expanding exposure to language experienced by the child. Our results question the idea that tests such as digit span are measuring a dedicated system for the temporary maintenance and manipulation of verbal material, and as such have implications for our understanding of those aspects of child development that are usually accounted for with respect to the operation of such a system. In particular, our results suggest that increases in STM performance do not play a causal role in language learning, but rather language learning itself is what causes increased performance in verbal STM tasks.

### Working memory and vocabulary breadth and depth: How they contribute to explain reading comprehension

*Paola Palladino (University of Pavia) & Caterina Artuso*

*Email: paola.palladino@unipv.it*

Vocabulary knowledge has been usually conceptualized and investigated as the number of words known (i.e., a measure of vocabulary breadth). However, research has shown the benefit of considering at least two dimensions of vocabulary knowledge: breadth and depth (e.g., Oakhill et al.,2015; Ouellette, 2006). In particular, these two dimensions have been related to reading comprehension showing contradictory results: for some researchers breadth has a stronger relation to comprehension that does depth (e.g., Tannenbaum, 2006), for some others breath predicts word encoding whereas depth predicts comprehension (Ouellette, 2006). The aim of the current study is to investigate how these two vocabulary dimensions account for variance in reading comprehension also considering the contribution of short-term and working memory, separately. Fifty children from third grade (mean age 8.4 years) were administered a series of tasks to assess their short-term memory, working memory, vocabulary depth (from the WISC IV) and breadth (taken from an Italian developmental neuropsychological assessment battery), and comprehension (assessed with an Italian standardized inferential comprehension task). Main finding indicated that working memory (but not short-term) explained vocabulary depth; vocabulary breadth was not accounted for by these memory measures. However, when both vocabulary breadth and depth, as well as memory measures, were entered to explain inferential reading comprehension, we found that WM lost its significance and vocabulary depth only accounted for reading comprehension. The study suggests the relevance to distinguish vocabulary breadth and depth in order to better capture the role of working memory in reading comprehension. It gives an original hint to sketch the mediational role of vocabulary depth from working memory to inferential reading comprehension.

### Resource reallocation in working memory through semantic chunks: Computational and behavioural evidence

*Benjamin Kowialiewski (Université Grenoble Alpes), Benoît Lemaire, & Sophie Portrat*

*Email: bkowialiewski@uliege.be*

**Introduction**: Many studies have shown that long-term memory knowledge, such as semantic knowledge, supports the short-term maintenance of verbal information in Working Memory (WM). For instance, it has been shown that to-be-remembered items related at the semantic level (e.g. leaf, tree, branch) are better recalled as compared to unrelated items (e.g. wall, sky, dog). However, the mechanisms underlying the influence of semantic knowledge in WM remain poorly understood. In this study, we took advantage of a convergent approach involving computational and behavioural methods to assess the possibility that semantic knowledge can be used in order to save WM resources that can be efficiently reallocated for maintenance purposes. 

**Methods & Results**: In an experiment requiring participants to perform immediate serial recall of lists composed of six memoranda (e.g. leaf - tree - branch - wall - sky - dog), we observed that the presence of a semantic chunk (i.e. leaf - tree - branch) enhanced recall performance for items that directly followed the semantic chunk (i.e. wall - sky - dog), and this compared to a condition where all the items were semantically unrelated (e.g. hammer - jacket - horn - wall - sky - dog). This phenomenon is successfully captured by a new computational architecture in which we integrated the activation occurring in the long-term memory linguistic system (Dell et al., 1997) within TBRS*, a decay-based WM model (Oberauer & Lewandowsky, 2011).

**Conclusion***: In this study, not only do we show for the first time that semantic knowledge can be used in order to save WM resources, but our simulations also demonstrate the potentialities offered by bridging the gap between WM and the activation in the long-term memory system.

### Does attentional refreshing modulate the associative relatedness effect in children and adults' working memory?

*Fiona Laura Rosselet-Jordan (University of Fribourg), Marléne Abadie, Stephanie Mariz Elsig, & Valérie Camos*

*Email: fionalaura.rosselet-jordan@unifr.ch*

Long-term memory (LTM) is known for affecting recall during working memory (WM) tasks. However, the way LTM intervenes in WM remains unknown. To test the predictions issued from different WM models (Barrouillet, Bernardin, & Camos, 2004; Cowan, 1999;  Rose, Buschsbaum, & Craik, 2014), the involvement of semantic LTM representations in a complex span task was manipulated through variations of the associative relatedness of the memory items, while the attentional demand of the concurrent task was varied to manipulate refreshing opportunities. Children and young adults were also compared, because children should use refreshing and relatedness cues less efficiently than adults. Despite the impact of the three main factors on recall performance which was better for related than unrelated words, with the low rather than the high demanding concurrent task and for adults than children, there was no interaction between associative relatedness and attentional demand neither in children nor in adults. We replicated these results in a second experiment with a more demanding secondary task. Moreover, the impact of the three mentioned factors was also analyzed on recall latency. In accordance with recall performance, participants, especially adults, were faster at recalling related (vs. unrelated) words, without any effect of the concurrent attentional demand on recall latency. The present findings suggest that the availability of attention does not modulate the effect of LTM on WM. We discuss how WM models can account for this finding and how LTM acts on WM functioning.

### No detrimental effect of semantic similarity on order memory: Could an encoding benefit be the explanation?

*Julia Krasnoff (University of Zurich), Eda Mizrak, & Klaus Oberauer*

*Email: j.krasnoff@psychologie.uzh.ch*

Similarity between items in a list can facilitate and impair working memory performance. For instance, phonological similarity enhances item but impairs order memory. This finding is explained by processes during retrieval where similar items serve as cues for each other, facilitating their retrieval but not necessarily in the right position. In two experiments using a serial-recall task with six-word lists we examined whether semantic similarity affects memory likewise. In experiment 1, semantic similarity was operationalized through 1) latent semantic analysis (LSA) or 2) categorical similarity. For both conditions, similarity improved item and, surprisingly, did not harm order memory. The effect was mainly driven by performance of the last three items, casting doubt on a solely retrieval-based explanation, which would predict similar effects for all items. In experiment 2, we tested whether there is an encoding benefit for semantically similar items that compensates the detrimental effect during retrieval. We considered the idea of an encoding resource (Popov & Reder, 2020) that depletes with each encoded item and combined it with the idea that similar items consume fewer resource due to activation of a common category at encoding. This leads to the prediction that items preceded by semantically similar items are left with more encoding resource and hence are better recalled even if being semantically unrelated. To test this, we manipulated similarity between first and second part of lists. Participants studied six-word lists of 1) similar, 2) dissimilar, 3) three similar followed by three dissimilar, 4) three dissimilar followed by three similar words. As predicted, performance for the second part was better when preceded by similar as compared to dissimilar words. This suggests that semantic similarity between items facilitates their encoding, saving encoding resource for the following items, and counteracting any detrimental effect of similarity at retrieval.

### The effects of spacing in incidental chunk learning

*Krzysztof Piątkowski (SWPS University), Katarzyna Zawadzka & Maciej Hanczakowski*

*Email: kpiatkowski1@swps.edu.pl*

To date, working memory studies examining chunking have mostly used procedures of deliberate learning. However, pre-experimentally established chunks examined in the working memory literature, such as well-known acronyms (e.g. FBI, CIA, IBM), are learned not intentionally, but rather acquired incidentally while performing tasks such as reading or problem solving. Here we examined how chunks are acquired and then utilized in a decision-making task requiring short-term memory maintenance. Using a variant of the task span paradigm (Logan, 2004), we repeatedly presented strings of letters, each denoting a binary decision to be made for visual stimuli. Performance in this task required short-term maintenance of strings in service of performing cognitive operations in a correct order. In the acquisition phase we manipulated whether repetitions of strings were massed or spaced. In the test phase, performance for strings from the acquisition phase was compared to performance for novel strings. In Experiment 1, both massed and spaced presentations improved performance when the same strings were re-used in the test phase, and to the same extent. In Experiment 2, memory load was introduced in the test phase in the form of to-be-remembered digits in order to assess whether newly created chunks free cognitive resources. Here again performance in the main task was equally facilitated for strings acquired in a massed and spaced fashion, but only chunks acquired in a spaced fashion improved performance in the secondary memory task. 
Our results suggest that memory chunks can be acquired incidentally, both by spaced and massed repetitions, and these chunks support redintegration responsible for reconstructing order of operations denoted by a chunk. On the other hand, only spaced acquisition seems to support chunks that not only help to redintegrate information but also to compress it when performing a complex task, so that additional information can be maintained in working memory.

### Working memory and categorization: How people code information in working memory when items share features?

*Gaën Plancher (University of Lyon) & Robert Goldstone*

*Email: gaen.plancher@univ-lyon2.fr*

A large literature suggests that the way we process information is influenced by the categories that we have learned. We examined whether when we try to uniquely encode items in working memory, the information encoded depends on the other stimuli being simultaneously learned. Participants were required to memorize unknown aliens, presented one at the time, for immediate recognition of their features. Some aliens, called twins, were organized into pairs that shared every feature (non-discriminative feature) except one (discriminative feature), while some other aliens, called hermits, did not share feature. We reasoned that if people develop unsupervised categories by creating a category for a pair of aliens, we should observe better feature identification performance for non-discriminative features compared to hermit features, but not compared to discriminative features. On the contrary, if distinguished feature draws attention, we should observe better performance when a discriminative rather than non-discriminative feature was probed. Our results showed that accuracy for non-discriminative features was equivalent to accuracy for discriminative features, but performance was greater for non-discriminative probes compared to hermit. Also, correlations in accuracy for parts in a twin were higher than correlations in accuracy for parts across twins. Finally, errors were greater for discriminative twin features than other kind of probes. This difference was accentuated by training, suggesting that features within the same cluster acquired equivalence over time. Overall, this suggests that when items share features, people code items in working memory by focusing on similarities between items, establishing clusters of items based in an unsupervised fashion not requiring feedback on cluster membership. 

### Impacts of anxiety on executive and perceptual attention in visual working memory

*David Spalding (University of Strathclyde), Louise A. Brown Nicholls, & Marc Obonsawin*

*Email: david.m.spalding@strath.ac.uk*

Trait anxiety is associated with deficits in attentional control, whereby top-down, directed executive control is diminished at the expense of bottom-up, perceptually driven attentional capture. Meanwhile, effective binding of features in visual working memory has been shown to rely on these processes, specifically when to-be-remembered objects are presented sequentially over time. Despite evidence for negative impacts of anxiety on visual working memory, there has been little study of the impacts of anxiety on binding specifically. Such studies would help to clarify the role of anxiety, and emotion more broadly, within multicomponent working memory models. Two studies will be presented that investigate the impact of trait anxiety on performance in a change detection, sequential binding task. Study 1 varied perceptual complexity, comparing memory for bindings (coloured shapes) to memory for individual features (blank shapes across varying array sizes (3 vs 4 items). Study 2 compared binding performance only. Participants performed either a concurrent task in which they count backwards from a two-digit number in threes - increasing executive demand - or repeat a two-digit number, a control condition engaging articulatory suppression. Outcomes will be measured in terms of performance effectiveness (proportion correct response accuracy) and efficiency (response times in trials in which a correct response was given). Results will indicate the extent to which trait anxiety impacts on visual feature binding in working memory, and the extent to which this is driven by specific anxiety symptoms (trait-cognitive or trait-somatic), task demand (memory for 3 or 4 items), attentional load (backwards counting or articulatory suppression), and/or memory type (binding or individual feature memory), as well as the potential interactions between these factors.

