# Internal, mental “actions”: How is information sustained in working memory?

Talks in this session cover the nature of refreshing in WM and how refreshing supports maintenance. This includes investigation of the retro-cue effect and the mechanisms underlying it, as well as the relationship between retrospective attention and working memory. This session also covers the topic of how WM maintenance processes (e.g. refreshing, binding) may change over the course of development/ageing.

## Schedule

This discussion session will take place 2 September from 15:00 - 16:30 (UK) / 16:00 - 17:30 (Switzerland/France) 

## Abstracts

Recorded talks will be available from 14 August 2020.

### Developmental changes in retrospective attention influence visual working memory precision

*Gaia Scerif (University of Oxford) & Andria Shimi*

*Email: gaia.scerif@psy.ox.ac.uk*

Visual working memory (VWM) improves dramatically during childhood but what drives this improvement is not well understood. One influential account thus far has been a simple increase in storage capacity. However, recent findings have shown that differences in the ability to use attention retrospectively to enhance the maintenance of internal representations are also important for understanding developmental improvements in VWM. Yet, changes in this ability are not the sole contributor to developmental differences in VWM performance. Indeed, additional findings have indicated developmental changes in VWM precision. In this study, we aimed to examine whether the developing ability to orient attention retrospectively to internal representations influences VWM precision differentially for children than for adults. To do so, we employed a paradigm that combined the continuous-recall VWM task with the partial-cueing report task. Specifically, seven-year-olds and young adults were asked to reproduce the colour of a probe item in a colour-wheel. The initial memory array, which included the probe item, could be uncued or followed by a spatial cue (retrocue) that directed participants' attention to a location in the memory array. Results showed that attentional biases engendered by retro-cues facilitated fidelity (overall precision) compared to uncued, baseline performance, for both age groups, but to a smaller degree in 7-year-olds compared to adults. Importantly, investigation of modelling parameters suggested that children demonstrate lower representational fidelity of items in VWM and that spatial attentional cues improve overall precision by increasing the probability of target storage, maintenance and recall, and by reducing misbinding errors as well as random guessing. These results extend our knowledge on the relation between retrospective attention and VWM development.

### On maintenance of continuous representation

*M. Labaronne (Universitè Lyon), S. Harding, R. Shiffrin, & G. Plancher*

*Email: maximilien.labaronne@univ-lyon2.fr*

Working memory performance for categorical items such as letters is a linear function of the cognitive load of a concurrent task, giving evidence that memory traces are maintained through attentional refreshing. The present study tested the effect of a concurrent load upon precision of memory for colors. Participants were asked to remember a series of three colors presented sequentially on a screen, each color was followed by three digits to be categorised. The cognitive load of the concurrent task was manipulated by varying the pace of digits presentation. At the end of the trial on a color wheel, participants were required to provide sequentially their best guess about the three colors they remembered, but also to provide a confident interval around their guesses. The same experiment was also conducted under articulatory suppression. Cognitive load affected the distance of the point estimate of color to the correct color, but not the width of the confidence interval, except for the third color.  Articulatory suppression decreased memory performance and confidence and this effect did not interact with cognitive load. These findings suggested that continuous representation can be maintained through attentional refreshing. 

### Investigating the differences between the types of bindings underlying working memory

*Maria Sanz Taberner (University of Essex) & Vanessa Loaiza*

*Email: msma17029@essex.ac.uk*

Binding,  or mentally  amalgamating different details of studied information,is  an  important  factor underlying working  memory  (WM).We  investigated the  potential dissociation between  different types of binding memory in an adaptive WM task (Bartsch et al., 2018), wherein participants studied three random letter pairs (e.g., L S, F‚Q, HX) each presented in different font colours (e.g., red, blue, green). Thereafter, participants were probed with one of the letters (e.g., F) from each pairing to recall its associated letter and font colours in two respective rows of three options: the correct target (e.g., Q, blue), a never-presented lure (e.g., Z, pink), and a lure from a different pair (e.g., S, red).The experiment comprised three blocks, each of them adjusting the presentation rate of subsequent trials based on the participants' colour accuracy, letter accuracy, and the combined accuracy of both details to achieve an approximate 67% criterion in each block. We applied a hierarchical Bayesian multinomial processing tree (MPT) model to the observed frequencies of the three different types of responses to derive latent parameter estimates of intrinsic binding memory (i.e., remembering the font colour of the presented pair of letters), extrinsic binding memory (i.e., remembering the pairing between the letters),and joint binding memory (e.g., integrating the letters with their font colour). We found that the presentation rate was sensitive to the block adjustment, such that the letter block (M= 1.77, SD= 1.03) was  faster  than  the  colour  block  (M=  3.30, SD=  1.06),  which  in  turn  was  faster  than  the combined block (M= 4.64, SD= 1.10). Interestingly, the block adjustment only impacted joint binding memory,  with no  credible  differences  between the  blocks  for  intrinsic or extrinsic  binding  memory. These results suggest a dissociation of the different types of binding underlying WM.

### Strategic prioritisation enhances young and older adults' visual feature binding in working memory

*Louise A. Brown Nicholls (University of Strathclyde), Amy Atkinson, & Richard J. Allen*

*Email: l.nicholls@strath.ac.uk*

Young (18-33 yrs) and older (60-90 yrs) adults' ability to retain visual feature bindings in working memory was assessed, as was the extent to which memory could be enhanced using strategic prioritisation. The task involved sequentially presenting three coloured shapes, followed by a test probe in the form of an individual colour or shape, and participants were asked to recall the accompanying feature. Based on previous evidence, the earlier sequential objects are most vulnerable to forgetting, and in older adults this is especially so for the middle object. In Experiment 1, participants were instructed either to focus on all objects equally, or to prioritise a particular object in the array that was deemed more valuable (i.e. more points would be awarded if that object was probed and recalled correctly). As older adults may not be as strategically flexible as young adults, they might differentially benefit from instructions to focus attention on certain objects, especially for the most vulnerable ones. As expected, young adults outperformed older adults overall. A general recency effect was also found, and the poorest performance was observed at the middle serial position. Additionally, both age groups were equally able to prioritise an object in visual working memory, with the largest effects observed at the most vulnerable middle position. Experiment 2 investigated the potential effect of increasing encoding time. This replicated the findings from Experiment 1, but further showed that, under these conditions, processing speed does not limit older adults' ability to benefit from strategic prioritisation. 


### Is inhibition in working memory domain-general? A study of age-related decline in cross-domain inhibitory abilities

*Coline Grégoire (Universitè de Liège) & Steve Majerus*

*Email: coline.gregoire@doct.uliege.be*

The unitary versus non-unitary nature of inhibitory control in working memory remains an open question: does inhibitory control deficit (i.e. to inhibit irrelevant information) appearing during aging concern all domains (language or visual information, etc.) or are they more important in certain areas (language) than others (visual information)? This study examines the specificity of inhibitory control by investigating the age-related decline in inhibitory abilities across several domains (visual, phonological and semantic) in an immediate target-probe matching task. 129 young adults (20-40 years old) and 130 elderly adults (60-80 years old) where presented two target stimuli and two probe stimuli (visual symbols, words or nonwords); they had to select the probe stimulus that was the most similar to both target stimuli based on visual, semantic or phonological similarity. In the inhibition condition, the wrong probe stimulus was pre-activated via a prime stimulus briefly occurring before the presentation of the target stimuli and thus had to be inhibited for correct response selection; in the facilitation condition, the correct probe stimulus was preactivated. An interference score was calculated by subtracting performance between the two conditions, for each stimulus domain. We observed that interference effects were overall larger in the elderly adults as compared to the young adult group. At the same time, there was decisive Bayesian evidence for an interaction between age group and stimulus domain, with particularly increased interference effects in the elderly group for the semantic and visual conditions. These results suggest domain general inhibition impairment at least for semantic and visual conditions in healthy aging. Differences in task sensitivity may account for the lesser inhibition impairment in the phonological domain. 

### Working memory and attention: A computational model of retro-cue effects

*Klaus Oberauer (University of Zurich)*

*Email: k.oberauer@psychologie.uzh.ch*

Directing attention to a subset of the contents of working memory improves the speed, and often the accuracy, of accessing the attended information. This can be demonstrated with the retro-cue paradigm (Souza & Oberauer, 2016), in which an item in the memory set is cued as most likely to be tested during the retention interval. Several mechanisms have been identified to underlie the retro-cue effect: The cued item's binding to its context is strengthened; the cued receives a head start for retrieval; it is being protected from visual interference from the test display, and other (not-cued) items are partially removed from working memory. I present a computational model - a connectionist version of the Interference Model of (Oberauer & Lin, 2017) - that implements these mechanisms. The model reproduces several findings with the retro-cue paradigm that have been diagnostic for the proposed mechanisms. 
Oberauer, K., & Lin, H.-Y. (2017). An interference model of visual working memory. Psychological Review, 124, 21-59. 
Souza, A. S., & Oberauer, K. (2016). In search of the focus of attention in working memory: 13 years of the retro-cue effect. Attention, Perception & Psychophysics, 78, 1839-1860. 

### The involvement of domain-general attention in the refreshing frequency effect

*Philippe Schneider (University of Fribourg), Evie Vergauwe & Valérie Camos*

*Email: philippe.schneider@unifr.ch*

In the guided refreshing paradigm (Souza, Rerko & Oberauer, 2014), 6 colored dots are simultaneously presented in different locations on screen at the beginning of a trial, followed by 4 sequentially presented arrows (here-after: retro-cues), each pointing to a location where a colored dot was presented at study. At the end of the trial, one of the locations is highlighted, and participants are tasked with reconstructing the color that was presented at this location during study, using a color wheel. The refreshing frequency effect is the fact that colors that are more often retro-cued between study and test, show better recall performance at the end of the trial. This effect has been replicated (Souza & Oberauer, 2017; Souza, Vergauwe & Oberauer, 2018), but its locus is still debated. The prevalent view stipulates that "thinking of" an item is similar to refreshing it (i.e., attentional refreshing account). The more an item is cued, the more it will be "thought of", the more it will be reactivated, thus better recalled. The aim of this experiment is to directly test this hypothesis, which has not already been done. Since attentional refreshing is thought to use executive attention, we reasoned that, if executive attention is diverted during the retro-cueing phase by a concurrent attention-demanding task, then the refreshing frequency effect should drastically diminish or even disappear. Conversely, the absence of such a reduction in the refreshing frequency effect would provide evidence against the attentional refreshing account. In this study, we tested this hypothesis by implementing a dual-task paradigm in which the guided refreshing paradigm is coupled with a variety of concurrent tasks that vary in their attentional demand. Results and implications of these results will be discussed.

### The efficiency of removal is independent from the accuracy of substitution in working memory updating

*Gidon T. Frischkorn (University of Zurich) & Claudia C. von Bastian*

*Email: gidon.frischkorn@psychologie.uzh.ch*

Memory tasks involving updating are among the best measures of working memory capacity. One process common to all updating tasks is the removal of old information that is to be substituted by new or transformed information. Previous studies have indicated that individual differences in the efficiency of removal are related to working memory capacity. These studies, however, often neglected the effect of removal on the accuracy of memory recall after the updating steps and did not report relationships between removal efficiency and the accuracy of substitution in memory. In this study, we re-analyzed data of four updating tasks that measured the efficiency of removal and the final recall accuracy to investigate the relationship between efficiency of removal and accuracy of substitution. Although the interval between cues to remove information and onset of the new information to be encoded showed large effects on the time taken to update information in memory, longer time to remove information before subsequent encoding of new information showed no effect on the accuracy of substitution. Moreover, individual differences in the ability to efficiently remove information were not related to individual differences in the final recall performance and thus accuracy of substitution. In sum, the ability to efficiently remove information from memory seems to be independent from the accuracy of substitution in tasks measuring working memory updating.

### Subsequent effects of free time on working memory performance

*Eda Mizrak (University of Zurich) & Klaus Oberauer*

*Email: eda.mizrak@psychologie.uzh.ch*

Increasing time to process information in working memory (WM) improves performance. However, it is unclear which processes are enabled by the free time that results in improved performance. One candidate process is short-term consolidation (STC), which makes WM representations stable (Ricker and Hardman, 2017). More free time after an item increases the probability that STC is completed.  If free time after item N affects STC of item N, this should a) improve memory for item N, and b) potentially improve memory of item N+1 because it eliminates the attentional blink caused by STC of item N. Hence, free time effects should be specific to the item preceding and following it. To test this prediction, in two serial-recall experiments we varied the position and duration of the free time within a seven-item study list consisting of consonants. In each trial, there was either a long gap (2.4 secs), a short gap (0.4 secs), or no gap added to one of the interstimulus intervals (ISI), whereas the remaining ISIs were all very short (0.1 secs). The contrast of the two gap conditions (short and long) with the no-gap control condition revealed the well-known advantage of temporal grouping. To understand, the effect of extra free time, we compared the effect of short vs. long gap on memory. Extra free time in the long gap condition improved recall of subsequent items in the list but not the items preceding it. This finding contradicts the predictions of the STC hypothesis. A more adequate explanation of our findings builds on the hypothesis of Popov and Reder (2020) that encoding events into memory temporarily depletes a resource. Free time given after an item enables replenishing of the encoding resource for the subsequent items. This explains why the beneficial effect accrues only for items following the long gap.  

### Freeing capacity in WM through the use of LTM representations

*Lea Bartsch (University of Zurich) & Peter Shepherdson*

*Email: l.bartsch@psychologie.uzh.ch*

Previous research has provided evidence that LTM strongly contributes to performance in WM tasks raising the question of how far active maintenance in WM can be replaced by the reliance on information stored in LTM. In two experiments we aimed to investigate whether the presence and use of LTM representations frees capacity for maintaining additional information in WM. In the first phase of experiment 1, we presented participants with word pairs for them to encode into LTM. Subsequently, they completed trials of a WM task, also involving word pairs. Crucially, the pairs presented in each WM trial consisted of varying numbers of new pairs (LTM unavailable) and the previously learned LTM pairs. The results provided evidence that recall performance in the WM task did not deteriorate when memory set size increased through the addition of LTM-available pairs, but that it did deteriorate when set size increased through adding LTM-unavailable (new) pairs. In a second experiment we investigated the robustness of this effect, by not only varying WM loads (2 and 4 pairs) but also varying LTM loads (0, 2, and 4 pairs). Recall performance decreased with LTM load for low WM load (2 pairs), but not to the level of performance with the same set size of only LTM-unavailable (new) pairs. In contrast, LTM load did not affect recall performance at higher WM load (4 pairs). This not only adds to the evidence of the first experiment, that individuals can outsource workload to LTM to optimise performance, but also speaks towards a WM system with a flexible gate to LTM that can be opened or closed depending on the current cognitive needs.