# Advances in measurement of working memory

To understand how working memory relates to other cognitive abilities and real-world behaviours, it is important to understand what our measures represent. The talks in this session address questions such as how measures of WM relate to other abilities, knowledge and strategies; and how these relationships change across the lifespan. We will also look at how well-known experimental effects and measures might be interpreted in a new light when examined in a different task or context.

## Schedule

This discussion session will take place 3 September from 14:00 - 15:30 (UK) / 15:00 - 16:30 (Switzerland/France) / 8:00 - 9:30 (USA Central Time)

## Abstracts

Recorded talks will be available from 14 August 2020.

### The Hebb repetition effect in Complex span tasks: Evidence towards the position-item association as its underlying mechanism

*Claudia Araya (Kyoto University), Klaus Oberauer, & Satoru Saito*

*Email: araya.claudia.23c@st.kyoto-u.ac.jp*

The Hebb repetition effect on a memory task refers to the improvement in the accuracy of recall of a repeated list (e.g., every 3 trials) over random non-repeated lists. Working memory tasks are often divided into simple span and complex span. Simple span refers to memory tasks in which participants are shown an uninterrupted sequence of memory items that need to be recalled in serial order at the end of the trial; complex span differs from simple span by the addition of processing items that do not need to be remembered (i.e. distractors) between each memory item. Previous research has shown that both temporal position and neighboring items need to be the same on each repetition list for the Hebb repetition effect to occur, meaning that chunking could be its underlying mechanism. Accordingly, one can expect absence of the Hebb repetition effect in a complex span task, given that the sequence is interrupted and chunking is unlikely. Nevertheless, one study by Oberauer, Jones, and Lewandowsky (2015) showed evidence of the Hebb repetition effect in a complex span task. However, further evidence was needed to confirm this finding. 
In Experiment 1, we replicated Oberauer et al.'s (2015) second experiment, confirming a strong Hebb repetition effect over 8 repetitions in a complex span task. For Experiments 2 and 3, we included distractors in both encoding and recall phases to avoid any resemblance to a simple span task and diminish every possibility of chunking. Results showed that the Hebb repetition effect was not affected by the distractors during encoding and recall, with both high and low cognitive load. A transfer cycle analysis showed that the long-term learning acquired in the complex span task can be transferred to a simple span task. These findings provide the first insights on the mechanism behind the Hebb repetition effect in complex span tasks; it is at least partially based on the cumulative association between each item and its temporal position. 

### The effect of cognitive load in working memory tasks: Limited to the complex span paradigm?

*Naomi Langerock (University of Geneva), Evie Vergauwe, Elena Throm, & Klaus Oberauer*

*Email: naomi.langerock@unige.ch*

The cognitive load effect is a well-established effect in the working memory literature. Increasing the cognitive load of a concurrent processing task results in a decrease of memory performance. The effect is robust regarding the kind of material used for both the memory and the processing task, and the effect has been observed in adult as well as in children, documenting its generalizability. However, the cognitive load effect seems to be mainly observed when using a complex span paradigm, which was most frequently used to explore its characteristics. The few studies using the Brown-Peterson paradigm to explore the cognitive load effect have often shown either no effect or a smaller effect (or needed a stronger manipulation of the cognitive load to observe the effect). The first goal of the present project was to asses in a within-study design whether the cognitive load effect differs in a typical complex span and a typical Brown-Peterson paradigm, while controlling for as much methodological differences as possible. The first experiment showed indeed a cognitive load effect in the complex span paradigm but not the Brown-Peterson paradigm. The second goal was to find out what may be driving this difference. The second experiment varied the total duration of the processing phases in both paradigms. Regardless of the total duration of processing, there was a cognitive load effect in the complex span but not the Brown-Peterson paradigm. The third experiment replicated this finding once more, and in addition compared two simple-span conditions in which the amount of free time in between presentation of items or after list presentation was varied. Longer free time in between items was beneficial for memory whereas free time added after list presentation was not. These results demonstrate a boundary condition for the cognitive load effect, and imply that both explanations proposed so far (Barrouillet et al., 2004; Oberauer et al.; 2012) are probably wrong. 

### Dual-task costs in working memory

*Pierre Barrouillet (University of Geneva), T. Minamoto, V. Camos, W.-T. Chooi, R.H. Logie, A. Morita, S. Nishiyama, & S. Saito*

*Email: Pierre.Barrouillet@unige.ch*

Working memory is the system devoted to the temporary maintenance of relevant information for ongoing cognitive activities. Due to its dual function of storage and processing, working memory structure and functioning have often been studied through the effect of one of these functions on the other, as for example in complex span or Brown Peterson tasks. The present study explored a different avenue of research by investigating the dual-task effects resulting from performing a response selection task (tone discrimination) while being subjected to an n-back task. The n-back task involved the presentation of series of letters, tones to be discriminated occurring in the intervals between two successive letters. Because the n-back task requires the continuous maintenance and updating of information in working memory, this paradigm allows the on-line assessment of the effect that this maintenance has on the concurrent response selection in terms of accuracy and response time, and conversely how this response selection affects maintenance and hence performance in the n-back task. For this purpose, the cognitive demand of both tasks were manipulated, with n varying from 0 to 2 in the n-back task, and the number of tones in the tone discrimination task varying from 1 to 3. While the memory load involved by the n-back task postponed and impaired tone discrimination, increasing the cognitive demand of this latter task had a detrimental effect on n-back speed and accuracy performance. Different theoretical approaches were compared in their capacity to account for these reciprocal effects observed between the two tasks.

### From "pure guess" to "absolute certain": What influences confidence judgments in visual working memory?

*Julia Krasnoff (University of Zurich), Klaus Oberauer, & Henrik Singmann*

*Email: j.krasnoff@psychologie.uzh.ch*

A long line of research on metacognition in long term memory (LTM) shows that metacognitive judgments are not a pure reflection of people's memory content but are influenced by several factors, such as general beliefs about one's memory capacity and situational cues. In contrast, a current model of visual working memory (VWM) confidence (van den Berg et al., 2017, Psychological Review) suggests that memory precision is directly mapped to confidence ratings through Fechner's law, implying that there are no other factors besides memory precision affecting confidence judgments. In three experiments we challenged this implicit assumption and examined the potential role of different factors for people's confidence judgments. In all experiments, participants were asked to complete a color reproduction task and to rate their confidence on a continuous scale. In the first two experiments, we manipulated task difficulty by varying set size (2,4, 8 colors) and used a color wheel (experiment 1) or a grey wheel (experiment 2) for recall. Results suggested that task difficulty itself is used as a cue for confidence in VWM. In experiment 3, we aimed to distinguish between the influence of perceived and objective task difficulty on confidence ratings. We manipulated objective difficulty by letting participants indicate their response on a color wheel (difficult) and on a grey wheel (easy) and manipulated perceived difficulty by varying the presentation duration (in a range that presumedly does not affect objective difficulty). In contrast to the first two experiments, results did not show any clear effects of manipulations on confidence. We test whether the data from all three studies can be fit by the confidence model of van den Berg and colleagues and discuss the need of additional parameters.   

### Does subjective awareness of working memory capacity limits improve with age?

*Alicia Forsberg (University of Missouri), Christopher L. Blume, & Nelson Cowan*

*Email: aliciaforsberg@missouri.edu*

To understand the limits of Working Memory (WM), researchers often estimate the number of items in memory (k) based on performance on change detection tasks. Typically, young adults are able to retain around 3 - 4 visual objects such as colored shapes in WM, whilst capacity appears lower in younger children. A child's judgment of their own WM will likely affect their actions. For instance, children may fail to obey directions if they do not realize that they have partially forgotten the directions. Similarly, insight into the limits of one's memory might be crucial for internal processes that strengthen or transform representations in WM. Such insight might prompt further encoding of a scene through prolonged attention or use of a mnemonic technique to boost memory, if one is aware that not all relevant items are encoded. This ability may also be an essential factor in age-related WM improvement in change detection tasks, where knowledge about the number of remembered items may be used to inform guessing (e.g., if one is aware of forgetting several items from a memory array, sometimes guessing that a seemingly novel probe was in fact part of the display is sensible). In three experiments, we investigated (1) participants' ability to accurately estimate how many items they remembered, and (2) whether this ability varied between children and adults. Children and adults estimated how many colored squares they remembered, in addition to performing a change detection task. We explored how memory retention intervals, visual pattern masks and set size influenced memory performance and meta-memory across age groups. Participants of all ages typically overestimated their WM capacity, and this tendency was greater in younger children. Interestingly, the average subjective estimated capacity - across age groups and a range of set sizes - was close to the often observed 3 - 4 object memory capacity limit.

### Where did the teddy bear go? Scaffolding maintenance strategies in visual working memory

*Christophe Fitamen (University of Fribourg), Agnés Blaye, & Valérie Camos*

*Email: christophe.fitamen@unifr.ch*

Working memory is a major predictor of cognitive development and school achievement. Noticeably, preschoolers exhibit poor performance in working memory tasks. It has been proposed that the absence of use of maintenance strategies before 7 years of age accounts for preschoolers' poor performance. In a first experiment, we examined how scaffolding maintenance strategies by location cues can improve working memory performance in 4- to 6-year-old preschoolers. In a complex span task, children memorized locations of a teddy bear who moved from one house to another, while they judged the upward/downward position of the bear in each house. During the retention interval, either houses disappeared or remained on screen, the latter providing location cues. Our findings showed that preschoolers benefited from the location cues, this effect remaining similar across age groups. The benefit can results because the location cues support either the goal maintenance in preschoolers known for presenting goal neglect or visual maintenance strategies. To disentangle between these two proposals, a second experiment with a similar methodology tested adults who should not benefit from any goal scaffolding, but could benefit from the scaffolding of maintenance strategies. Although no evidence supported an effect on the entire adults sample, low-span adults, but not the high-span, took advantage of location cues. Together, these results suggest that working memory performance can be improved in preschoolers and in adults with low span when the task embeds elements that can scaffold their maintenance strategies.

### On the development of working memory updating in preschoolers

*Sabrina Panesi (National Research Council of Italy, Institute for Educational Technology), Alessia Bandettini, Chiara Giordano, Laura Traverso, & Sergio Morra*

*Email: panesi.sabrina@gmail.com*

A group of 176 preschoolers (36-74 months) was administered an updating task (Magic house; Panesi & Morra, 2017) along with three tests of M capacity, as defined in the theory of constructive operators: Backward Word Span (BWS), Mr. Cucumber (Cuc), and Direction Following Task (DFT). The Magic house is essentially a running span task for young children. The Magic house correlated .44 with BWS, .38 with Cuc, .45 with DFT, and .52 with the average of three, all p<.001; and with age partialled out, .21, .19, .24 (all ps <.01) , and .31 (p<.001), respectively. Instead, the correlation between Magic house and age (.45) was no longer significant (r=.11) when M capacity was statistically removed. Descriptive statistics indicate a linear increase of Magic house mean scores as a function of either age or M capacity. Performance on the Magic house was defined as low (<50% correct, i.e. no more than one animal per item on average), intermediate (between 50 and 75% correct), or high (>75% correct). Cross-classification prediction analysis indicated as "impossible event" a low performance on the Magic house by children with an M capacity of 3 units, Del = .87, z=6.72,.99 CI = (.54, 1.20). Events defined as low performance on the Magic house by children with an M capacity of at least 2 units, and high performance on the Magic house by children with an M capacity of 1 unit, were rare but not impossible, Del = .54, z=4.08, p<.001, .99 CI = (.20, .89), and Del = .62, z=5.10, p<.001, .99 CI = (.31, .94), respectively. Overall, the results indicate that updating skill, in preschoolers, depends closely on M capacity but does not coincide with it.

### Assessing perceptual and internal attention in the aging mind

*Alessandra Souza (University of Zurich) & Klaus Oberauer*

*Email: a.souza@psychologie.uzh.ch*

Attention refers to the ways in which the brain controls its own information processing by selecting and prioritizing inputs that match current task goals. Perceptual attention modulates incoming sensory information. Attention to working memory, conversely, operates upon representations maintained only in mind. These two types of attention can be deployed to portions of the spatial environment (spatial attention) or to specific features such as a color or shape (feature-based attention). Yet, we still lack knowledge about the separability (or unity) of these abilities. Here we will report the results of a battery of 20 tasks that assessed individual and age differences in several aspects of attentional focusing (i.e., spatial attention, feature-based attention, and attention to working memory), perceptual abilities, reasoning, and working memory capacity. Students (18-35 years old; N = 172) and seniors (65-80 years old; N = 174) participated in the study. For the attention tasks, we computed attention-benefit scores indicating how much performance improved when people used a cue to focus their spatial attention, feature-based attention, and attention to working memory. Within each of these domains, we will discuss the reliability of measurement of this focusing benefit, how much they correlate with each other, with other attention abilities and related cognitive domains. 

### Collective working memory

*Yoav Kessler (Ben-Gurion University of the Negev)*

*Email: kesslery@bgu.ac.il*

The human cognitive ability to process information, make decisions, and act upon the world is remarkable. However, at the same time, our cognitive abilities are profoundly limited and imperfect. Recent theorizing in cognitive sciences suggests an intriguing  answer to this question, being that the limitations inherent to individual cognitive functioning are mitigated by human's reliance on collective cognition. However, relatively little is known about basic cognitive processes at the group level. In a series of studies we aimed to examine the concept of collective working memory (WM), being the ability of groups to maintain, manipulate and use information in a dynamic and goal-directed manner, over short time periods. Notably, the potential ability to share WM content and processing among group members can potentially resolve the tension between the central role of WM in cognition on the one hand, and its strict limitation on the other, by providing means to extend WM beyond the individual's limits. I will present initial results from three related projects conducted toward answering the following questions, all utilizing the change detection task: (a) can individual-level WM capacity be extended by social interaction, and if so‚ how and to what extent? (b) can the wisdom of crowds phenomenon harnessed to increase collective WM capacity compared to individual capacity? and (c) what is the capacity of "real" interacting groups, and how it is related to the capacity of their members.


